<?php if (!defined('APPLICATION')) exit(); ?>

<div>
<h1>User Agreement</h1>
<p>&nbsp;</p>
<p style="margin-bottom:15px;">Please read this user agreement carefully before using the Studentbox.</p>
<p style="margin-bottom:15px;">BY USING STUDENTBOX, YOU AGREE TO BE BOUND BY THE TERMS OF THIS AGREEMENT. IF YOU DON'T AGREE TO THE TERMS, DON'T USE THE STUDENTBOX WEBSITE ("Studentbox").</p>
<p style="margin-bottom:15px;">Studentbox is exclusively for the use of year 10, 11 &amp; 12 students in Western Australia. Curtin University* ("Curtin University is a trademark of Curtin University of Technology") reserves the right to immediately terminate the registration of any person which is found to be false, misleading or the person is otherwise ineligible to register on Studentbox.</p>
<ol>
<li style="margin-bottom:15px;"><strong>Restrictions.</strong> This agreement allows you to use Studentbox. You may not rent, lease, lend, redistribute or sub-licence Studentbox. You shall not exploit Studentbox&nbsp; in any unauthorised way whatsoever, including but not limited to, by trespass or burdening network capacity. YOU MUST NOT UPLOAD OR USE THE STUDENTBOX WEBSITE TO SEND ANY DEFAMATORY, ILLEGAL, OFFENSIVE, BULLYING OR OTHERWISE OBJECTIONABLE MATERIAL. Nevertheless, you agree to use Studentbox website at your sole risk and Curtin University shall have no liability to you for content that may be found to be offensive, indecent, objectionable or harmful.</li>
<li style="margin-bottom:15px;"><strong>Rights of the supplier</strong>. Curtin University reserves the right to change, suspend, remove, or disable access to Studentbox at any time without notice. IN PARTICULAR, CURTIN UNIVERSITY MAY AT ITS SOLE DISCRETION CHANGE, SUSPEND, REMOVE OR DISABLE YOUR ACCESS TO STUDENTBOX IF IT CONSIDERS THAT YOU ARE RESPONSIBLE FOR UPLOADING OR USING STUDENTBOX TO SEND ANY DEFAMATORY, ILLEGAL, OFFENSIVE, INDECENT, HARASSING, BULLYING OR OTHERWISE OBJECTIONABLE MATERIAL. In no event will Curtin University be liable for the removal or disabling of access to Studentbox.</li>
<li style="margin-bottom:15px;"><strong>Curtin University's service</strong>. The Studentbox web site and the services provided to you on and via this web site are provided on an "as is" basis. You agree that Curtin University, or its designated representative(s), reserve the right to modify or discontinue provision of this web site and its services, and to remove the data you provide, either temporarily or permanently, at any time, without notice and without any liability towards you. Curtin University, or its designated representative(s), will not be held responsible or liable for timeliness, removal of information, failure to store information, inaccuracy of information, or improper delivery of information.</li>
<li style="margin-bottom:15px;"><strong>Your responsibilities and registration obligations</strong>. In order to use certain parts of this website, you will be required to register for a user account; in this case, you agree to provide truthful information when requested. By registering for a user account, you explicitly agree to this site's User Agreement, including any amendments made by Curtin University that are published herein.</li>
<li style="margin-bottom:15px;"><strong>Privacy policy.</strong> Registration data, profile data and other personally identifiable information that the site may collect is subject to the terms of the Studentbox Privacy Policy.<br>
Please refer to the <a href="http://www.studentbox.com.au/page/privacy-1">Studentbox Privacy Policy</a> for further information.</li>
<li style="margin-bottom:15px;"><strong>Registration and password.</strong> You are responsible for maintaining the confidentiality of your password, and you will be responsible for all usage of your user account and/or user name, whether authorised or not authorised by you. You agree to immediately notify Curtin University of any unauthorised use of your user account, user name or password.</li>
<li style="margin-bottom:15px;"><strong>Your conduct</strong>. You agree that all information or data of any kind, whether text, software, code, music or sound, photographs or graphics, video or other materials ("content"), made available publicly or privately, will be under the sole responsibility of the person providing the said content, or of the person whose user account is used. Although the University will endeavour to filter all content you agree that this web site may inadvertently expose you to content that may be objectionable or offensive. The University will not be responsible to you in any way for content displayed on this web site, nor for any error or omission.<br>
By using this web site or any service provided, you explicitly agree that:<br>
a)&nbsp;you will not provide any content or conduct yourself in any way that may be construed as: unlawful; illegal; threatening; harmful; abusive; harassing; stalking; defamatory; libellous; vulgar; obscene; offensive; objectionable; designed to interfere with or disrupt the operation of this web site or any service provided; infected with a virus or other destructive or deleterious programming routine; giving rise to civil or criminal liability; or in violation of an applicable local, national or international law;<br>
b)&nbsp;you will not impersonate or misrepresent your association with any person or entity; you will not forge or otherwise seek to conceal or misrepresent the origin of any content provided by you;<br>
c)&nbsp;you will not collect or harvest any information about other users;<br>
d)&nbsp;you will not provide, and you will not use this web site to provide, any content or service in any commercial manner, or in any manner that would involve junk mail, spam, or any other form of unauthorised advertising or commerce; you will not use this web site to promote or operate any service or content without the University or its representative(s) prior written consent;<br>
e)&nbsp;you will not provide any content that may give rise to the University being held civilly or criminally liable, or that may be considered a violation of any local, national or international law, including - but not limited to - laws relating to copyrights, trademarks, patents, or trade secrets.</li>
<li style="margin-bottom:15px;"><strong>Submission of content on this web site</strong>. By providing any content to this web site:<br>
a)&nbsp;you acknowledge and agree that Curtin University will have the right (but not obligation), at the Community Coordinator's sole&nbsp; discretion, to refuse to publish, or to remove, or to block access to any content you provide, at any time and for any reason, with or without notice.</li>
<li style="margin-bottom:15px;"><strong>Third-party services.</strong> Goods and services of third parties may be advertised and/or may be made available on or through this web site. Representations made regarding products and services provided by third parties will be governed by the policies and representations made by these third parties. Curtin University will not in any manner be liable for or responsible for any of your dealings or interaction with third parties.</li>
<li style="margin-bottom:15px;"><strong>Notification of copyright infringement.</strong> If you believe that your property has been used in any way that could be considered a copyright infringement or a violation of your intellectual property rights, please notify the Community Coordinator via email <a href="mailto:admin@studentbox.com.au" target="_blank">admin@studentbox.com.au</a></li>
<li style="margin-bottom:15px;"><strong>Computer viruses.</strong> While Curtin University makes reasonable efforts to ensure that all content provided on Studentbox does not contain computer viruses, you are responsible for taking the appropriate precautions to scan for computer viruses and to ensure that you have a complete and current back up of the applicable items contained on your computer system.</li>
<li style="margin-bottom:15px;"><strong>Opinions of others.</strong> Statements and opinions expressed in any interactive forums, instant messages, comments sections, contributed works, excerpts and elsewhere on Studentbox are not necessarily those of Curtin University. Curtin University offers Studentbox and the information contained herein without any warranty of any kind, expressed or implied, and is not liable for its accuracy, mistakes, errors, or omissions of any kind, nor for any loss or damage caused by a user's reliance on information obtained from Studentbox.</li>
<li style="margin-bottom:15px;"><strong>Third-party content</strong>. You understand that certain content may include materials from third parties. You acknowledge and agree that Curtin University is not responsible for evaluating the content or accuracy of any third-party material or website, nor does it warrant, endorse or assume any liability or responsibility for any third-party materials or websites or their products.</li>
<li style="margin-bottom:15px;"><strong>Storage of information and data on Studentbox.</strong> You acknowledge and agree not to use Studentbox as a storage device for your personal computing needs. To the extent not prohibited by law, in no event shall Curtin University be liable for any loss or damage incurred by you arising from the loss or damage to any information or data you have stored on Studentbox.</li>
<li style="margin-bottom:15px;"><strong>Agreement term.</strong> This agreement is effective until terminated. Your rights under this agreement will terminate automatically without notice from Curtin University if you fail to comply with any term(s) of this agreement. Upon the termination of this agreement, you shall cease all use of Studentbox.</li>
<li style="margin-bottom:15px;"><strong>Disclaimer of warranties.</strong> YOU ACKNOWLEDGE AND AGREE THAT USE OF STUDENTBOX SOFTWARE IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY OF CONTENT AND EFFORT IS WITH YOU. CURTIN UNIVERSITY DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN STUDENTBOX WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF STUDENTBOX WILL BE UNINTERRUPTED OR ERROR-FREE OR THAT DEFECTS IN STUDENTBOX OR SERVICES WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY CURTIN UNIVERSITY OR ITS REPRESENTATIVES SHALL CREATE A WARRANTY.</li>
<li style="margin-bottom:15px;"><strong>Limitation of liability.</strong> To the extent not prohibited by law, in no event shall Curtin University be liable for personal injury, or any incidental, special, indirect or consequential damages whatsoever, including, without limitation, damages for loss of profits, loss of data, business interruption or any other commercial damages or losses, arising out of or related to your use or inability to use Studentbox.</li>
<li style="margin-bottom:15px;"><strong>Controlling law and severability.</strong> This agreement will be governed by and construed in accordance with the laws of Western Australia. If for any reason a court of competent jurisdiction finds any provision or portion thereof to be unenforceable, the remainder of this agreement shall continue in full force and effect.</li>
<li style="margin-bottom:15px;"><strong>Amendments</strong>. No amendment to or modification of this agreement will be binding unless in writing and signed by Curtin.</li>
<li style="margin-bottom:15px;"><strong>Language.</strong> Any translation of this agreement is done for local requirements and in the event of a dispute between the English and any non-English versions, the English version of this agreement shall govern.</li>
<li style="margin-bottom:15px;"><strong>Copyright note.</strong> Studentbox may be used to reproduce materials, but only for reproduction of materials in which you own the copyright or materials you are authorised or legally permitted to reproduce.&nbsp; You agree that Studentbox concept, including but not limited to graphics, audio clips, editorial content and portal content, contain proprietary information and material that is not owned by you and is protected by relevant intellectual property and other laws. No portion of Studentbox concept may be reproduced in any form or by any means without the expressed permission in writing from Curtin University. You agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on Studentbox, in any manner. If you are uncertain about your right to copy or permit access to any material you should contact your legal advisor.<br>
<em>International Students: This software is intended for Australian citizens and permanent residents only. Refer to international.curtin.edu.au for Future International Students information.</em><br>
CRICOS provider code WA 00301J, NSW 02637B</li>
</ol></div>
                    
        